// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/message/proto/message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/stevenkitter/skills/common/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailVerifyReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailVerifyReq) Reset()         { *m = SendEmailVerifyReq{} }
func (m *SendEmailVerifyReq) String() string { return proto.CompactTextString(m) }
func (*SendEmailVerifyReq) ProtoMessage()    {}
func (*SendEmailVerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3d584df27fa7f4, []int{0}
}

func (m *SendEmailVerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailVerifyReq.Unmarshal(m, b)
}
func (m *SendEmailVerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailVerifyReq.Marshal(b, m, deterministic)
}
func (m *SendEmailVerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailVerifyReq.Merge(m, src)
}
func (m *SendEmailVerifyReq) XXX_Size() int {
	return xxx_messageInfo_SendEmailVerifyReq.Size(m)
}
func (m *SendEmailVerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailVerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailVerifyReq proto.InternalMessageInfo

func (m *SendEmailVerifyReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailVerifyReq)(nil), "proto.SendEmailVerifyReq")
}

func init() {
	proto.RegisterFile("services/message/proto/message.proto", fileDescriptor_9e3d584df27fa7f4)
}

var fileDescriptor_9e3d584df27fa7f4 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x87, 0xf1, 0xf4, 0xc0, 0x3c, 0x21, 0x56, 0x30, 0x25, 0x25, 0x99, 0x9c, 0x9f, 0x9b,
	0x9b, 0x9f, 0x07, 0x55, 0x02, 0xe1, 0x40, 0x54, 0x28, 0x69, 0x71, 0x09, 0x05, 0xa7, 0xe6, 0xa5,
	0xb8, 0xe6, 0x26, 0x66, 0xe6, 0x84, 0xa5, 0x16, 0x65, 0xa6, 0x55, 0x06, 0xa5, 0x16, 0x0a, 0x89,
	0x70, 0xb1, 0xa6, 0x82, 0x44, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x23, 0x07,
	0x2e, 0xe6, 0x60, 0xdf, 0x60, 0x21, 0x4b, 0x2e, 0x7e, 0x34, 0x2d, 0x42, 0x92, 0x10, 0xd3, 0xf4,
	0x30, 0x8d, 0x92, 0xe2, 0x86, 0x4a, 0x05, 0xa5, 0x16, 0x17, 0x38, 0x99, 0x47, 0x99, 0xa6, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x97, 0xa4, 0x96, 0xa5, 0xe6, 0x65,
	0x67, 0x96, 0x94, 0xa4, 0x16, 0xe9, 0x17, 0x67, 0x67, 0xe6, 0xe4, 0x14, 0xeb, 0x63, 0xf7, 0x56,
	0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x4d, 0x66, 0x8b, 0xf7, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SMSClient is the client API for SMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SMSClient interface {
	SendEmailVerify(ctx context.Context, in *SendEmailVerifyReq, opts ...grpc.CallOption) (*proto1.Resp, error)
}

type sMSClient struct {
	cc *grpc.ClientConn
}

func NewSMSClient(cc *grpc.ClientConn) SMSClient {
	return &sMSClient{cc}
}

func (c *sMSClient) SendEmailVerify(ctx context.Context, in *SendEmailVerifyReq, opts ...grpc.CallOption) (*proto1.Resp, error) {
	out := new(proto1.Resp)
	err := c.cc.Invoke(ctx, "/proto.SMS/SendEmailVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSServer is the server API for SMS service.
type SMSServer interface {
	SendEmailVerify(context.Context, *SendEmailVerifyReq) (*proto1.Resp, error)
}

func RegisterSMSServer(s *grpc.Server, srv SMSServer) {
	s.RegisterService(&_SMS_serviceDesc, srv)
}

func _SMS_SendEmailVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailVerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServer).SendEmailVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SMS/SendEmailVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServer).SendEmailVerify(ctx, req.(*SendEmailVerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SMS",
	HandlerType: (*SMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailVerify",
			Handler:    _SMS_SendEmailVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/message/proto/message.proto",
}
